### ISSUE TITLE
More than one file was found with OS independent path 'javax/annotation/CheckReturnValue.java'

### ISSUE THREAD

**Issue by priyansh360** [abhi5658/search-youtube#1]
uses or overrides a deprecated API. |   In MainActivity
-- | --
G:\android projects\PGTesting\app\src\main\java\com\darkweb\android\pgtesting\MainActivity.java:
uses or overrides a deprecated API.
Recompile with -Xlint:deprecation for details.

**Comment by abhi5658** [comment]
If you are directly running my whole project, ensure that all the dependency data gets downloaded properly.
I debugged  the code today, it's still running fine.
Make sure you use a working Youtube API key.
Also ensure you have a look at build.gradle in app folder, any change the dependency according to your downloaded sdk, otherwise perform a "Invalidate caches and restart" in file menu.

In build.gradle I had  a merge error of conflicting dependencies, so I added  the configuration

I will commit the latest changes, after that you can check.

**Comment by abhi5658** [comment]
I deleted a line in video item xml file which was causing error.
Now you can run it smoothly.
